name: test and deploy
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: loading code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: running test
        run: npm test
  deployment:
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
      - name: loading code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: isntall dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: deploy to digital ocean
        run: echo "the project is being deployed..."