name: Deploy website
on: 
    push:
        branches:
            - main
            - 'activity_*'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - run: npm run build
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: dist-files
                path: dist
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: download artifact from github server
              uses: actions/download-artifact@v3
              with:
                name: dist-files #make sure it is the same name as when you upload the artifact
            - name: output contents
              run: ls
            - run: echo "Deploying...."