name: job output & caching
on:
    push:
        branches:
            - "activity_*"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: caching dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}
                # this is the hash of package-lock.json file which has all the dependencies
            - run: npm ci
            # we still needs this command as if the cache is not up to date, it will install the dependencies
            - run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        outputs: 
            file-name: ${{ steps.js-file-name.outputs.file-name }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: actions/cache@v3
              with:
                path: ~/.npm
                key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}
            - run: npm ci
            - run: npm run build
            - name: creating the file name
              id: js-file-name
              run: find dist/assets/*.js -type f -execdir echo "file-name={}" >> $GITHUB_OUTPUT ";"
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: echo "this is the file name ${{ needs.build.outputs.file-name }}"
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: actions/cache@v3
              with:
                path: ~/.npm
                key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}
            - run: echo "Deploying..."